### ISSUE TITLE
Backend Integration: User facing pages

### ISSUE THREAD

**Issue by sonylomo** [SpaceyaTech/Web-Redesign-Core#17]
# Description
The website has some buttons that require backend integration. 
You'll have to tag me in case you don't know the link to the backend API (for security purposes and keep out the bad guys). 🙂

# Tasks

1. Home page

- [ ] _Join the community_ button: direct user to sign up page (`/api/users/`)

2. About Us

- [ ] _Partner with us_ button: direct user to sign up page (`/api/users/`)

3. Resources

- [ ] List resource cards from (`/api/resourcetypes/`)
~~- [ ] _Explore_ button: direct user to individual resource page (`/api/resourcetypes/{id}/`)~~

4. Community

- [ ] List event cards from (`/api/events/`) on the _**community**_ page
- [ ] List all event cards and categories from (`/api/events/`) on the _**allevents**_ page
~~- [ ] Display event details from (`http://34.175.147.171:8000/api/events/{id}/`) to individual event view~~
- [ ] _Join_ button: direct user to sign up page (`/api/users/`)

5. Blog

- [ ] List all blog cards from (`/api/blog/`)
- [ ] List all categories from (`/api/category/`)
- [ ] `Read more` button leading to individual blog display from (`/api/blog/{id}/`)
